name: "푸시로 작동시키기"

on: [push]

permissions:
  contents: write
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Push 작성',
              body: 'Push로 작성하였습니다'
            })